
export const SET_LOCATION = 'SET_LOCATION';

export const SET_ROUTES = 'SET_ROUTES';

export const SET_ROUTESLATLNG = 'SET_ROUTESLATLNG';

export const SET_STARTPOSITION = 'SET_STARTPOSITION';

export const DEL_STARTPOSITION = 'DEL_STARTPOSITION';

export const SET_ENDPOSITION = 'SET_ENDPOSITION';

export const DEL_ENDPOSITION = 'DEL_ENDPOSITION';

export const SET_STARTSITES = 'SET_STARTSITES';

export const DEL_STARTSITES = 'DEL_STARTSITES';

export const SET_ENDSITES = 'SET_ENDSITES';

export const DEL_ENDSITES = 'DEL_ENDSITES';